all:
	pdflatex ClassicModel.tex > /dev/null 2>&1
	pdflatex NewModel.tex > /dev/null 2>&1

clean:
	find . -name \*.log -type f -delete
	find . -name \*.aux -type f -delete
	find . -name \*.gz -type f -delete







