all:
	pdflatex Model1.tex > /dev/null 2>&1
	pdflatex Model2.tex > /dev/null 2>&1

clean:
	find . -name \*.log -type f -delete
	find . -name \*.aux -type f -delete
	find . -name \*.gz -type f -delete







