all:
	pdflatex HumanIcon.tex > /dev/null 2>&1
	pdflatex MonkeyIcon.tex > /dev/null 2>&1

clean:
	find . -name \*.log -type f -delete
	find . -name \*.aux -type f -delete
	find . -name \*.gz -type f -delete







