all:
	pdflatex Rod-Bipolar-Off > /dev/null 2>&1
	pdflatex Rod-Bipolar-On > /dev/null 2>&1
	pdflatex Rod-Bipolar-Pathway-OffOn > /dev/null 2>&1
	pdflatex Rod-Bipolar-Pathway-OnOff > /dev/null 2>&1

clean:
	find . -name \*.log -type f -delete
	find . -name \*.aux -type f -delete
	find . -name \*.gz -type f -delete







